module.exports = {
    navigation: {
        backgroundColor: "#222222",
        color: "#f1f4f6",
        display: "inline-block",
        width: "100%",
        fontFamily: "'Open Sans', sans-serif",
        position: "fixed",
        zIndex: "1"
    },
    linkItem: {
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
		color: "#fff",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 15px 15px",
	    cursor: "pointer",
    },
    linkItemHover: {
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
		color: "#fff",
		backgroundColor: "#4d4d4d",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 12px 15px",
	    cursor: "pointer",
	    borderBottom: "3px solid #009933",
    },
    linkSubItem: {
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
		color: "#fff",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 15px 15px",
	    cursor: "pointer",
    },
    linkSubItemHover: {
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
		color: "#fff",
		backgroundColor: "#195380",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 15px 12px",
	    cursor: "pointer",
	    borderLeft: "3px solid #da383c",
    },
}