module.exports = {
  headerContainer: {
    fontFamily: "'Poiret One', cursive",
  },
  navigation: {
    backgroundColor: "#f4f4f4",
    color: "#3b3a36",
    display: "inline-block",
    width: "100%",
    position: "fixed",
    zIndex: "1",
  },
  navigationMobile: {
    backgroundColor: "#f4f4f4",
    color: "#3b3a36",
    display: "inline-block",
    width: "100%",
  },
  logo: {
    height: "60px",
    float: "left",
    paddingLeft: "10px"
  },
  noSpace: {
    padding: "0",
    margin: "0",
  },
  menuContainer: {
    position: "absolute",
    top: "0",
    right: "0",
  },
  noSpaceFloat: {
    padding: "0",
    margin: "0",
    float: "right",
  },
  title: {
    textDecoration: "none",
    color: "#3b3a36",
    fontWeight: "700",
    display: "inline-block",
    padding: "10px 5px",
    cursor: "pointer",
    fontSize: "32px",
  },
  menu: {
    float: "left",
    margin: "0",
    padding: "0",
  },
  menuMobile: {
    float: "right",
    width: "100%",
    margin: "0",
    padding: "0",
  },
  subMenu: {
    display: "none",
    margin: "0",
    padding: "0",
    width: "350px",
    display: "none",
    zIndex: "1",
    position: "fixed",
    top: "65px",
    right: "0",
    backgroundColor: "transparent",
    maxWidth: "100%",
  },
  menuItem: {
    color: "#3b3a36",
    height:"65px",
    listStyle: "none",
    padding: "18px 45px",
    fontSize: "22px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemHover: {
    backgroundColor:"#ccc",
    color: "#3b3a36",
    height:"65px",
    listStyle: "none",
    padding: "18px 45px",
    fontSize: "22px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuSubItem: {
    backgroundColor:"#c36b74",
    color: "#f4f4f4",
    height:"65px",
    listStyle: "none",
    padding: "18px 20px",
    fontSize: "18px",
    cursor: "pointer",
  },
  menuSubItemHover: {
    backgroundColor:"#a3434c",
    color: "#f4f4f4",
    height:"65px",
    listStyle: "none",
    padding: "18px 20px",
    fontSize: "18px",
    cursor: "pointer",
  },
  menuNavButton: {
    backgroundColor:"#3b3a36",
    color: "#f4f4f4",
    height:"65px",
    listStyle: "none",
    padding: "18px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuNavButtonHover: {
    backgroundColor:"#282725",
    color: "#f4f4f4",
    height:"65px",
    listStyle: "none",
    padding: "18px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  }
}
