module.exports = {
  navigation: {
    backgroundColor: "#f4f4f4",
    color: "#3b3a36",
    display: "inline-block",
    width: "100%",
    fontFamily: "'Poiret One', cursive",
    position: "fixed",
    zIndex: "1",
    fontSize: "22px",
  },
  title: {
    textDecoration: "none",
    color: "#3b3a36",
    fontWeight: "700",
    display: "inline-block",
    padding: "10px 15px",
    cursor: "pointer"
  },
  menu: {
    float: "right",
    margin: "0",
    padding: "0",
  },
  subMenu: {
    display: "none",
    float: "right",
    margin: "0",
    padding: "0",
  },
  menuItem: {
    backgroundColor:"#3c948b",
    color: "#f4f4f4",
    height:"51px",
    listStyle: "none",
    padding: "11px 45px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuItemHover: {
    backgroundColor:"#2c6d66",
    color: "#f4f4f4",
    height:"51px",
    listStyle: "none",
    padding: "11px 45px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuSubItem: {
    backgroundColor:"#c36b74",
    color: "#f4f4f4",
    height:"51px",
    listStyle: "none",
    padding: "11px 45px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuSubItemHover: {
    backgroundColor:"#a3434c",
    color: "#f4f4f4",
    height:"51px",
    listStyle: "none",
    padding: "11px 45px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuNavButton: {
    backgroundColor:"#3b3a36",
    color: "#f4f4f4",
    height:"51px",
    listStyle: "none",
    padding: "11px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuNavButtonHover: {
    backgroundColor:"#282725",
    color: "#f4f4f4",
    height:"51px",
    listStyle: "none",
    padding: "11px 25px",
    fontSize: "18px",
    cursor: "pointer",
    display: "inline-block",
  },
  menuNav: {
    display: "none",
    zIndex: "2",
    padding: "0",
    position: "absolute",
    top: "0",
    right: "0",
    backgroundColor: "transparent",
  }
}
