module.exports = {
    navigation: {
        backgroundColor: "#222222",
        color: "#f1f4f6",
        display: "inline-block",
        width: "100%",
        fontFamily: "'Open Sans', sans-serif",
        position: "fixed",
        zIndex: "1"
    },
    menu: {
    	float: "right",
    },
    title: {
		textDecoration: "none",
		color: "#fff",
		fontSize: "22px",
		fontWeight: "700",
		color: "#fff",
		display: "inline-block",
		padding: "10px 0 10px 0",
		cursor: "pointer",
    },
    signIn: {
		color: "#fff",
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 15px 15px",
	    cursor: "pointer",
    },
    signInHover: {
		color: "#fff",
		backgroundColor: "#4d4d4d",
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 12px 15px",
	    cursor: "pointer",
	    borderBottom: "3px solid #009933",
    },
    signUp: {
		color: "#fff",
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 15px 15px",
	    cursor: "pointer",
    },
    signUpHover: {
		color: "#fff",
		backgroundColor: "#4d4d4d",
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 12px 15px",
	    cursor: "pointer",
	    borderBottom: "3px solid #FD8A10",
    },
    linkItem: {
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
		color: "#fff",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 15px 15px",
	    cursor: "pointer",
    },
    linkItemHover: {
		textDecoration: "none",
		touchAction: "manipulation",
		userSelect: "none",
		WebkitUserSelect: "none",
		msUserSelect: "none",
		color: "#fff",
		backgroundColor: "#4d4d4d",
	    fontSize: "16px",
	    fontWeight: "300",
	    display: "inline-block",
	    padding: "15px 15px 12px 15px",
	    cursor: "pointer",
	    borderBottom: "3px solid #009933",
    },
}
