module.exports = {
  textarea: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    cursor: "pointer",
    border: "1px solid #ccc",
    backgroundColor: "#fdfdfd",
  },
  textareaFocused: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    border: "1px solid #3c948b",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
  textareaHovered: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "pointer",
    backgroundColor: "#ffffff",
  },
  textareaHoveredFocused: {
    width: "100%",
    maxWidth: "100%",
    minHeight: "115px",
    maxHeight: "350px",
    padding: "0 6px 0 8px",
    border: "1px solid #3c948b",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
}
