module.exports = {
  container: {
    color: "#3b3a36",
    margin: "0",
    minHeight: "100%",
  },
  jumbotron: {
    fontFamily: "'Rokkitt', serif",
    textAlign: "center",
    padding: "200px 0",
    margin: "0",
  },
  tumbotron: {
    backgroundColor:"#3c948b",
    color: "#f4f4f4",
    fontFamily: "'Rokkitt', serif",
    textAlign: "center",
    padding: "20px 0",
    margin: "0",
    fontSize: "16px",
  },
  tumbotronHovered: {
    backgroundColor:"#2c6d66",
    color: "#f4f4f4",
    fontFamily: "'Rokkitt', serif",
    textAlign: "center",
    padding: "20px 0",
    margin: "0",
    fontSize: "16px",
    cursor: "pointer",
  },
  gumbotron: {
    backgroundColor:"#c36b74",
    color: "#f4f4f4",
    fontFamily: "'Rokkitt', serif",
    textAlign: "center",
    padding: "20px 0",
    margin: "0",
    fontSize: "16px",
  },
  mumbotron: {
    fontFamily: "'Poiret One', cursive",
    textAlign: "center",
    padding: "20px 0",
    margin: "0",
    backgroundColor:"#f4f4f4",
    fontSize: "16px",
  },
  text: {
    fontFamily: "'Rokkitt', serif",
  },
  img: {
    maxWidth: "100%",
  },
}
