module.exports = {
  select: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "pointer",
    backgroundColor: "#fdfdfd",
  },
  selectFocused: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #3c948b",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
  selectHovered: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #ccc",
    cursor: "pointer",
    backgroundColor: "#ffffff",
  },
  selectHoveredFocused: {
    width: "100%",
    height: "40px",
    lineHeight: "30px",
    padding: "0 6px 0 8px",
    border: "1px solid #3c948b",
    cursor: "auto",
    backgroundColor: "#ffffff",
  },
}
