module.exports = {
  container: {
    margin: "0",
    padding: "0px",
    display: "block",
    position: "relative",
    height: "15px",
  },
  header: {
    backgroundColor: "transparent",
    cursor: "default",
    height: "15px",
    width: "35px",
    overflow: "hidden",
    display: "inline-block",
    whiteSpace: "nowrap",
    position: "absolute",
    top: "0px",
    left: "0px",
  },
  body: {
    backgroundColor: "#f4f4f4",
    padding: "0px",
    height: "15px",
    overflow: "hidden",
    display: "inline-block",
    position: "absolute",
    top: "0px",
    left: "35px",
  },
  ruler: {
    margin: "0px",
    padding: "0px",
    listStyle: "none",
    display: "inline-block",
    color: "#ccc",
    height: "15px",
    overflow: "hidden",
  },
  rulerItem: {
    margin: "0px",
    padding: "0px",
    listStyle: "none",
    display: "inline-block",
    width: "1in",
    textAlign: "right",
  },
}
